# Generated by Django 3.0.2 on 2020-01-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardapp', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
